name: PHPUnit Tests

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    name: Run PHPUnit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: curl, dom, mbstring, zip, json

      - name: Install dependencies
        run: composer install --no-progress

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit --configuration phpunit.xml